[workspace]
changelog_config = "cliff.toml"
publish_timeout = "10m"

[[package]]
name = "jolt_core"
publish = true

[[package]]
name = "jolt_quickjs"
publish = true

[[package]]
name = "jolt_jsc"
publish = true
publish_no_verify = true

[[package]]
name = "jolt_web"
publish = true

[[package]]
name = "jolt_rs"
publish = true

[[package]]
name = "flutter_jolt"
publish = false
release = false
