// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 1038876270;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'flutter_jolt',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',

      );
}

abstract class RustLibApi extends BaseApi {
  Future<JsValue> crateApiSimpleJoltRuntimeCallFunction({
    required JoltRuntime that,
    required String name,
    required List<JsValue> args,
  });

  Future<JsValue> crateApiSimpleJoltRuntimeEval({
    required JoltRuntime that,
    required String code,
  });

  Future<JsValue> crateApiSimpleJoltRuntimeEvalAsync({
    required JoltRuntime that,
    required String code,
  });

  Future<JsValue> crateApiSimpleJoltRuntimeGetGlobal({
    required JoltRuntime that,
    required String name,
  });

  JoltRuntime crateApiSimpleJoltRuntimeNew();

  Future<void> crateApiSimpleJoltRuntimeSetGlobal({
    required JoltRuntime that,
    required String name,
    required JsValue value,
  });

  Future<void> crateApiSimpleInitApp();

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_JoltRuntime;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_JoltRuntime;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_JoltRuntimePtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<JsValue> crateApiSimpleJoltRuntimeCallFunction({
    required JoltRuntime that,
    required String name,
    required List<JsValue> args,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJoltRuntime(
            that,
            serializer,
          );
          sse_encode_String(name, serializer);
          sse_encode_list_js_value(args, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_js_value,
          decodeErrorData: sse_decode_jolt_error,
        ),
        constMeta: kCrateApiSimpleJoltRuntimeCallFunctionConstMeta,
        argValues: [that, name, args],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleJoltRuntimeCallFunctionConstMeta =>
      const TaskConstMeta(
        debugName: "JoltRuntime_call_function",
        argNames: ["that", "name", "args"],
      );

  @override
  Future<JsValue> crateApiSimpleJoltRuntimeEval({
    required JoltRuntime that,
    required String code,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJoltRuntime(
            that,
            serializer,
          );
          sse_encode_String(code, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_js_value,
          decodeErrorData: sse_decode_jolt_error,
        ),
        constMeta: kCrateApiSimpleJoltRuntimeEvalConstMeta,
        argValues: [that, code],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleJoltRuntimeEvalConstMeta =>
      const TaskConstMeta(
        debugName: "JoltRuntime_eval",
        argNames: ["that", "code"],
      );

  @override
  Future<JsValue> crateApiSimpleJoltRuntimeEvalAsync({
    required JoltRuntime that,
    required String code,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJoltRuntime(
            that,
            serializer,
          );
          sse_encode_String(code, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_js_value,
          decodeErrorData: sse_decode_jolt_error,
        ),
        constMeta: kCrateApiSimpleJoltRuntimeEvalAsyncConstMeta,
        argValues: [that, code],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleJoltRuntimeEvalAsyncConstMeta =>
      const TaskConstMeta(
        debugName: "JoltRuntime_eval_async",
        argNames: ["that", "code"],
      );

  @override
  Future<JsValue> crateApiSimpleJoltRuntimeGetGlobal({
    required JoltRuntime that,
    required String name,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJoltRuntime(
            that,
            serializer,
          );
          sse_encode_String(name, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_js_value,
          decodeErrorData: sse_decode_jolt_error,
        ),
        constMeta: kCrateApiSimpleJoltRuntimeGetGlobalConstMeta,
        argValues: [that, name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleJoltRuntimeGetGlobalConstMeta =>
      const TaskConstMeta(
        debugName: "JoltRuntime_get_global",
        argNames: ["that", "name"],
      );

  @override
  JoltRuntime crateApiSimpleJoltRuntimeNew() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
        },
        codec: SseCodec(
          decodeSuccessData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJoltRuntime,
          decodeErrorData: sse_decode_jolt_error,
        ),
        constMeta: kCrateApiSimpleJoltRuntimeNewConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleJoltRuntimeNewConstMeta =>
      const TaskConstMeta(debugName: "JoltRuntime_new", argNames: []);

  @override
  Future<void> crateApiSimpleJoltRuntimeSetGlobal({
    required JoltRuntime that,
    required String name,
    required JsValue value,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJoltRuntime(
            that,
            serializer,
          );
          sse_encode_String(name, serializer);
          sse_encode_box_autoadd_js_value(value, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_jolt_error,
        ),
        constMeta: kCrateApiSimpleJoltRuntimeSetGlobalConstMeta,
        argValues: [that, name, value],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleJoltRuntimeSetGlobalConstMeta =>
      const TaskConstMeta(
        debugName: "JoltRuntime_set_global",
        argNames: ["that", "name", "value"],
      );

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_JoltRuntime => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJoltRuntime;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_JoltRuntime => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJoltRuntime;

  @protected
  JoltRuntime
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJoltRuntime(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return JoltRuntimeImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  JoltRuntime
  dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJoltRuntime(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return JoltRuntimeImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  JoltRuntime
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJoltRuntime(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return JoltRuntimeImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  JsValue dco_decode_box_autoadd_js_value(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_js_value(raw);
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  JoltError dco_decode_jolt_error(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return JoltError_EvalError(
          message: dco_decode_String(raw[1]),
          stack: dco_decode_opt_String(raw[2]),
        );
      case 1:
        return JoltError_ConversionError(dco_decode_String(raw[1]));
      case 2:
        return JoltError_RuntimeError(dco_decode_String(raw[1]));
      case 3:
        return JoltError_FunctionNotFound(dco_decode_String(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  JsEntry dco_decode_js_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return JsEntry(
      key: dco_decode_String(arr[0]),
      value: dco_decode_js_value(arr[1]),
    );
  }

  @protected
  JsValue dco_decode_js_value(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return JsValue_Undefined();
      case 1:
        return JsValue_Null();
      case 2:
        return JsValue_Bool(dco_decode_bool(raw[1]));
      case 3:
        return JsValue_Int(dco_decode_i_64(raw[1]));
      case 4:
        return JsValue_Float(dco_decode_f_64(raw[1]));
      case 5:
        return JsValue_String(dco_decode_String(raw[1]));
      case 6:
        return JsValue_Array(dco_decode_list_js_value(raw[1]));
      case 7:
        return JsValue_Object(dco_decode_list_js_entry(raw[1]));
      case 8:
        return JsValue_Bytes(dco_decode_list_prim_u_8_strict(raw[1]));
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  List<JsEntry> dco_decode_list_js_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_js_entry).toList();
  }

  @protected
  List<JsValue> dco_decode_list_js_value(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_js_value).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  JoltRuntime
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJoltRuntime(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return JoltRuntimeImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  JoltRuntime
  sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJoltRuntime(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return JoltRuntimeImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  JoltRuntime
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJoltRuntime(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return JoltRuntimeImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  JsValue sse_decode_box_autoadd_js_value(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_js_value(deserializer));
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  JoltError sse_decode_jolt_error(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_message = sse_decode_String(deserializer);
        var var_stack = sse_decode_opt_String(deserializer);
        return JoltError_EvalError(message: var_message, stack: var_stack);
      case 1:
        var var_field0 = sse_decode_String(deserializer);
        return JoltError_ConversionError(var_field0);
      case 2:
        var var_field0 = sse_decode_String(deserializer);
        return JoltError_RuntimeError(var_field0);
      case 3:
        var var_field0 = sse_decode_String(deserializer);
        return JoltError_FunctionNotFound(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  JsEntry sse_decode_js_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_key = sse_decode_String(deserializer);
    var var_value = sse_decode_js_value(deserializer);
    return JsEntry(key: var_key, value: var_value);
  }

  @protected
  JsValue sse_decode_js_value(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        return JsValue_Undefined();
      case 1:
        return JsValue_Null();
      case 2:
        var var_field0 = sse_decode_bool(deserializer);
        return JsValue_Bool(var_field0);
      case 3:
        var var_field0 = sse_decode_i_64(deserializer);
        return JsValue_Int(var_field0);
      case 4:
        var var_field0 = sse_decode_f_64(deserializer);
        return JsValue_Float(var_field0);
      case 5:
        var var_field0 = sse_decode_String(deserializer);
        return JsValue_String(var_field0);
      case 6:
        var var_field0 = sse_decode_list_js_value(deserializer);
        return JsValue_Array(var_field0);
      case 7:
        var var_field0 = sse_decode_list_js_entry(deserializer);
        return JsValue_Object(var_field0);
      case 8:
        var var_field0 = sse_decode_list_prim_u_8_strict(deserializer);
        return JsValue_Bytes(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  List<JsEntry> sse_decode_list_js_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <JsEntry>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_js_entry(deserializer));
    }
    return ans_;
  }

  @protected
  List<JsValue> sse_decode_list_js_value(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <JsValue>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_js_value(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJoltRuntime(
    JoltRuntime self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as JoltRuntimeImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJoltRuntime(
    JoltRuntime self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as JoltRuntimeImpl).frbInternalSseEncode(move: false),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerJoltRuntime(
    JoltRuntime self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as JoltRuntimeImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_js_value(JsValue self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_js_value(self, serializer);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_jolt_error(JoltError self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case JoltError_EvalError(message: final message, stack: final stack):
        sse_encode_i_32(0, serializer);
        sse_encode_String(message, serializer);
        sse_encode_opt_String(stack, serializer);
      case JoltError_ConversionError(field0: final field0):
        sse_encode_i_32(1, serializer);
        sse_encode_String(field0, serializer);
      case JoltError_RuntimeError(field0: final field0):
        sse_encode_i_32(2, serializer);
        sse_encode_String(field0, serializer);
      case JoltError_FunctionNotFound(field0: final field0):
        sse_encode_i_32(3, serializer);
        sse_encode_String(field0, serializer);
    }
  }

  @protected
  void sse_encode_js_entry(JsEntry self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.key, serializer);
    sse_encode_js_value(self.value, serializer);
  }

  @protected
  void sse_encode_js_value(JsValue self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case JsValue_Undefined():
        sse_encode_i_32(0, serializer);
      case JsValue_Null():
        sse_encode_i_32(1, serializer);
      case JsValue_Bool(field0: final field0):
        sse_encode_i_32(2, serializer);
        sse_encode_bool(field0, serializer);
      case JsValue_Int(field0: final field0):
        sse_encode_i_32(3, serializer);
        sse_encode_i_64(field0, serializer);
      case JsValue_Float(field0: final field0):
        sse_encode_i_32(4, serializer);
        sse_encode_f_64(field0, serializer);
      case JsValue_String(field0: final field0):
        sse_encode_i_32(5, serializer);
        sse_encode_String(field0, serializer);
      case JsValue_Array(field0: final field0):
        sse_encode_i_32(6, serializer);
        sse_encode_list_js_value(field0, serializer);
      case JsValue_Object(field0: final field0):
        sse_encode_i_32(7, serializer);
        sse_encode_list_js_entry(field0, serializer);
      case JsValue_Bytes(field0: final field0):
        sse_encode_i_32(8, serializer);
        sse_encode_list_prim_u_8_strict(field0, serializer);
    }
  }

  @protected
  void sse_encode_list_js_entry(List<JsEntry> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_js_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_list_js_value(List<JsValue> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_js_value(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}

@sealed
class JoltRuntimeImpl extends RustOpaque implements JoltRuntime {
  // Not to be used by end users
  JoltRuntimeImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  JoltRuntimeImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_JoltRuntime,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_JoltRuntime,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_JoltRuntimePtr,
  );

  Future<JsValue> callFunction({
    required String name,
    required List<JsValue> args,
  }) => RustLib.instance.api.crateApiSimpleJoltRuntimeCallFunction(
    that: this,
    name: name,
    args: args,
  );

  Future<JsValue> eval({required String code}) => RustLib.instance.api
      .crateApiSimpleJoltRuntimeEval(that: this, code: code);

  Future<JsValue> evalAsync({required String code}) => RustLib.instance.api
      .crateApiSimpleJoltRuntimeEvalAsync(that: this, code: code);

  Future<JsValue> getGlobal({required String name}) => RustLib.instance.api
      .crateApiSimpleJoltRuntimeGetGlobal(that: this, name: name);

  Future<void> setGlobal({required String name, required JsValue value}) =>
      RustLib.instance.api.crateApiSimpleJoltRuntimeSetGlobal(
        that: this,
        name: name,
        value: value,
      );
}
