// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'simple.freezed.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<JoltRuntime>>
abstract class JoltRuntime implements RustOpaqueInterface {
  Future<JsValue> callFunction({
    required String name,
    required List<JsValue> args,
  });

  Future<JsValue> eval({required String code});

  Future<JsValue> evalAsync({required String code});

  Future<JsValue> getGlobal({required String name});

  factory JoltRuntime() => RustLib.instance.api.crateApiSimpleJoltRuntimeNew();

  Future<void> setGlobal({required String name, required JsValue value});
}

@freezed
sealed class JoltError with _$JoltError implements FrbException {
  const JoltError._();

  const factory JoltError.evalError({required String message, String? stack}) =
      JoltError_EvalError;
  const factory JoltError.conversionError(String field0) =
      JoltError_ConversionError;
  const factory JoltError.runtimeError(String field0) = JoltError_RuntimeError;
  const factory JoltError.functionNotFound(String field0) =
      JoltError_FunctionNotFound;
}

class JsEntry {
  final String key;
  final JsValue value;

  const JsEntry({required this.key, required this.value});

  @override
  int get hashCode => key.hashCode ^ value.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is JsEntry &&
          runtimeType == other.runtimeType &&
          key == other.key &&
          value == other.value;
}

@freezed
sealed class JsValue with _$JsValue {
  const JsValue._();

  const factory JsValue.undefined() = JsValue_Undefined;
  const factory JsValue.null_() = JsValue_Null;
  const factory JsValue.bool(bool field0) = JsValue_Bool;
  const factory JsValue.int(PlatformInt64 field0) = JsValue_Int;
  const factory JsValue.float(double field0) = JsValue_Float;
  const factory JsValue.string(String field0) = JsValue_String;
  const factory JsValue.array(List<JsValue> field0) = JsValue_Array;
  const factory JsValue.object(List<JsEntry> field0) = JsValue_Object;
  const factory JsValue.bytes(Uint8List field0) = JsValue_Bytes;
}
